# @package _global_
# Override configuration for gigahand dataset
dataset_name: gigahand
robot_type: xhand
embodiment_type: bimanual
task: p36-tea
data_id: 10
horizon: 2.0
temperature: 1.0
pos_noise_scale: 0.05
